---
driver:
  name: docker
  use_sudo: false
  privileged: true

platforms:
  - name: ubuntu
    driver_config:
      run_command: /lib/systemd/systemd

suites:
  - name: core

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X -p git -p curl -p sudo
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .idea/
    - .git/
    - .gitignore
    - .gitlab-ci.yml
    - .kitchen/
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - tests/
  dependencies:
    - name: munin
      repo: git
      source: https://gitlab.dylanwilson.dev/infrastructure/salt-formulas/munin-formula.git
  state_top:
    base:
      "*":
        - core
  pillars:
    top.sls:
      base:
        "*":
          - core
    core.sls:
      munin_node:
        log_level: 4
        log_file: /var/log/munin/munin-node.log
        pid_file: /var/run/munin/munin-node.pid
        background: 1
        setsid: 1
        user: root
        group: root
        ignore_file:
          - "[\\#~]$"
          - "DEADJOE$"
          - "\\.bak$"
          - "%$"
          - "\\.dpkg-(tmp|new|old|dist)$"
          - "\\.rpm(save|new)$"
          - "\\.pod$"
        host_name: {{ grains['host'] }}
        allow:
          - ^127\.0\.0\.1$
          - ^::1$
        host: "*"
        port: 4949
